default: &default
  #adapter: jdbcpostgresql
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  host: localhost
  database: horse_zone_development
  username: postgres
  password: postgres

test:
  <<: *default
  host: localhost
  database: horse_zone_test
  username: postgres
  password: postgres

production:
  <<: *default
  host: localhost
  database: horse_zone_production
  username: postgres
  password: postgres
