# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1a65c4954d72c93b7530ec99a2d841950c5e1dbfe8a65e5e0f0fe93e3e8a2352995914a58a9485de6b17ac70e992d8782269424812b7a4ab4d629a14ab1cd5b

test:
  secret_key_base: f7e8d6038c37d07b9c3402e848df1b645bdef265dcf7fead186f2f189937898c97cb7a554a661e7ea6560c7a0e7bab1b47f5873d21eaa56b07f447ddf71511dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
